const Map<String, dynamic> person = {
  'entity': 'person',
  'label': 'Person',
  'defaultSort': {'key': 'name', 'ascending': true},
  'fields': [
    {
      'key': 'id',
      'label': '#',
      'type': 'number',
      'sortable': true,
      'filterable': false,
      'searchable': false,
    },
    {
      'key': 'name',
      'label': 'Name',
      'type': 'string',
      'sortable': true,
      'filterable': true,
      'searchable': true,
    },
    {
      'key': 'age',
      'label': 'Age',
      'type': 'number',
      'sortable': true,
      'filterable': true,
      'searchable': false,
    },
    {
      'key': 'city',
      'label': 'City',
      'type': 'string',
      'sortable': true,
      'filterable': true,
      'searchable': true,
    },
    {
      'key': 'email',
      'label': 'Email',
      'type': 'email',
      'sortable': true,
      'filterable': true,
      'searchable': true,
    },
  ],
  'actions': ['edit', 'delete'],
};

const Map<String, dynamic> article = {
  'entity': 'article',
  'label': 'Article',
  'defaultSort': {'key': 'id', 'ascending': true},
  'fields': [
    {
      'key': 'id',
      'label': '#',
      'type': 'number',
      'sortable': true,
      'filterable': false,
      'searchable': false,
    },
    {
      'key': 'title',
      'label': 'Title',
      'type': 'string',
      'sortable': true,
      'filterable': true,
      'searchable': true,
    },
    {
      'key': 'description',
      'label': 'Description',
      'type': 'string',
      'sortable': false,
      'filterable': true,
      'searchable': true,
    },
    {
      'key': 'body',
      'label': 'Body',
      'type': 'string',
      'sortable': false,
      'filterable': false,
      'searchable': true,
    },
    {
      'key': 'published',
      'label': 'Status',
      'type': 'bool',
      'sortable': true,
      'filterable': true,
      'searchable': false,
      'filterOptions': ['true', 'false'],
    },
  ],
  'actions': ['edit', 'delete'],
};
